var list = [
	"Like A Rolling Stone",
	"Satisfaction",
	"Imagine",
	"What's Going On",
	"Respect",
	"Good Vibrations",
	"Johnny B. Goode",
	"Hey Jude",
	"Smells Like Teen Spirit",
	"What'd I Say",
	"My Generation",
	"A Change Is Gonna Come",
	"Yesterday",
	"Blowin' In The Wind",
	"London Calling",
	"I Want To Hold Your Hand",
	"Purple Haze",
	"Maybellene",
	"Hound Dog",
	"Let It Be",
	"Born To Run",
	"Be My Baby",
	"In My Life",
	"People Get Ready",
	"God Only Knows",
	"(Sitting On) The Dock Of The Bay",
	"Layla",
	"A Day In The Life",
	"Help",
	"I Walk The Line",
	"Stairway To Heaven",
	"Sympathy For The Devil",
	"River Deep, Mountain High",
	"You've Lost That Loving Feeling",
	"One",
	"No Woman No Cry",
	"Gimme Shelter",
	"That'll Be The Day",
	"Dancing In The Streets",
	"The Weight",
	"Waterloo Sunset",
	"Tutti Frutti",
	"Georgia On My Mind",
	"Heartbreak Hotel",
	"Heroes",
	"All Along The Watchtower",
	"Bridge Over Troubles Water",
	"Hotel California",
	"The Tracks Of My Tears"
];

module.exports=list;